services:
  db:
    image: postgis/postgis:15-3.3
    container_name: memoria_curitibana_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASS:-admin123}
      POSTGRES_DB: ${DB_NAME:-memoriacuritibana}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  pgdata: