from datetime import date

from pydantic import BaseModel, ConfigDict, Field

from memoria_curitibana.domains.archive.models import ArchiveReviewStatus


class ArchiveDocumentDTO(BaseModel):
    """
    Strict Insert/Update Contract for the Archive Layer.

    Acts as the guardian of the fact table's integrity. Ensures that migration
    scripts and multiple Artificial Intelligence workers carry complete, typed
    payloads when updating the document's enrichment state.
    """

    description_id: str = Field(description="ID inherited from Silver.")
    original_title: str = Field(description="Original title from Silver.")
    document_date: date | None = Field(default=None, description="Document date.")
    summary: str | None = Field(default=None, description="Document summary.")
    staging_content_hash: str = Field(description="Lineage control hash and change detection (CDC).")
    original_thumbnail_url: str | None = Field(
        default=None, description="Public download link of the thumbnail at the source."
    )
    storage_thumbnail_uri: str | None = Field(
        default=None, description="URI or internal path of the file saved in the Object Storage"
    )

    # --- ISAD(G) Standard Metadata ---
    reference_code: str | None = Field(default=None, description="Archival reference code.")
    level: str | None = Field(default=None, description="Description level (e.g. Dossier, Item, Volume).")
    producers: str | None = Field(default=None, description="Producing entities responsible for the fonds/document.")
    admin_bio_history: str | None = Field(
        default=None, description="Administrative history or biography of the producer."
    )
    admin_archival_history: str | None = Field(
        default=None, description="Archival history (chain of custody of the document)."
    )
    provenance: str | None = Field(default=None, description="Provenance / origin of the record.")
    scope_content: str | None = Field(
        default=None, description="Scope and content (detailed description of the textual content)."
    )
    language_name: str | None = Field(default=None, description="Predominant language in the descriptive document.")
    archivist_notes: str | None = Field(
        default=None, description="Notes and technical observations of the archivist who cataloged it."
    )

    # --- Enrichment (Machine Learning) ---
    final_title: str | None = Field(default=None, description="Title generated by the AI or revised.")

    execution_log: dict[str, str] = Field(
        default_factory=dict,
        description="Tracks which workers (AI) have already processed the document. E.g.: {'ner_spacy': 'DONE'}",
    )

    # --- Governance (Human-In-The-Loop) ---
    review_status: ArchiveReviewStatus = Field(
        default=ArchiveReviewStatus.PENDING_AI, description="Current audit status."
    )
    is_anomaly: bool = Field(default=False, description="Structural error flag.")
    anomaly_reasons: list[str] | None = Field(default=None, description="List of errors found.")

    model_config = ConfigDict(from_attributes=True)


class DocumentTagSummary(BaseModel):
    """Streamlined tag attached to a document when reading the collection."""

    tag_id: int
    name: str

    model_config = ConfigDict(from_attributes=True)


class DocumentEntitySummary(BaseModel):
    """Streamlined named entity (NER) attached to a document."""

    entity_id: int
    name: str
    entity_type: str

    model_config = ConfigDict(from_attributes=True)


class DocumentMacroCategorySummary(BaseModel):
    """Vote of one macro category over the tags of a document."""

    category_id: int
    name: str
    tag_count: int

    model_config = ConfigDict(from_attributes=True)


class DocumentSummary(BaseModel):
    """Read view of the collection, consumed by the API and the front-end."""

    description_id: str
    original_title: str
    final_title: str | None = None
    document_date: date | None = None
    review_status: ArchiveReviewStatus
    is_anomaly: bool = False
    storage_thumbnail_uri: str | None = None
    scope_content: str | None = None
    admin_bio_history: str | None = None
    tags: list[DocumentTagSummary] = Field(default_factory=list)
    entities: list[DocumentEntitySummary] = Field(default_factory=list)
    # Majority vote over ``tags``: how many of this document's tags belong to each
    # macro category, ordered by count. Built by the repository on read.
    macro_categories: list[DocumentMacroCategorySummary] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class DocumentListResponse(BaseModel):
    """Page of collection results."""

    total: int
    limit: int
    offset: int
    items: list[DocumentSummary]
