from datetime import date, datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from scrinalia.domains.archive.models import ArchiveReviewStatus
from scrinalia.domains.archive.schemas.responses import RouteResponse


class ArchiveDocumentDTO(BaseModel):
    """
    Strict Insert/Update Contract for the Archive Layer.

    Acts as the guardian of the fact table's integrity. Ensures that migration
    scripts and multiple Artificial Intelligence workers carry complete, typed
    payloads when updating the document's enrichment state.
    """

    description_id: str = Field(description="ID inherited from Silver.")
    original_title: str = Field(description="Original title from Silver.")
    document_date: date | None = Field(default=None, description="Document date.")
    summary: str | None = Field(default=None, description="Document summary.")
    staging_content_hash: str = Field(description="Lineage control hash and change detection (CDC).")
    original_thumbnail_url: str | None = Field(
        default=None, description="Public download link of the thumbnail at the source."
    )
    storage_thumbnail_uri: str | None = Field(
        default=None, description="URI or internal path of the file saved in the Object Storage"
    )

    # --- ISAD(G) Standard Metadata ---
    reference_code: str | None = Field(default=None, description="Archival reference code.")
    #: Rung of the level catalogue resolved from the declared text. ``None`` when the source
    #: declares a level the catalogue does not know: the load does **not** fail, the node is
    #: left unclassified and the diagnostics report it as ``UNKNOWN_LEVEL``.
    level_id: int | None = Field(default=None, description="Description level (catalogue FK).")
    producers: str | None = Field(default=None, description="Producing entities responsible for the fonds/document.")
    admin_bio_history: str | None = Field(
        default=None, description="Administrative history or biography of the producer."
    )
    admin_archival_history: str | None = Field(
        default=None, description="Archival history (chain of custody of the document)."
    )
    provenance: str | None = Field(default=None, description="Provenance / origin of the record.")
    scope_content: str | None = Field(
        default=None, description="Scope and content (detailed description of the textual content)."
    )
    language_name: str | None = Field(default=None, description="Predominant language in the descriptive document.")
    archivist_notes: str | None = Field(
        default=None, description="Notes and technical observations of the archivist who cataloged it."
    )
    access_conditions: str | None = Field(
        default=None,
        description="ISAD(G) 4.1: conditions governing access. Parsed by staging and, until this "
        "field existed here, silently dropped by the transfer.",
    )

    # --- Enrichment (Machine Learning) ---
    final_title: str | None = Field(default=None, description="Title generated by the AI or revised.")

    #: Position in the arrangement, when the source declares one. Both are **optional on purpose**
    #: and they mean "the source said nothing": the INSERT then falls back to the column default (a
    #: root path) and the ON CONFLICT leaves whatever curation placed untouched. Sending them is how
    #: a declared parent wins — which is the whole contract of H6, and the reason the transfer can
    #: no longer be trusted to always speak about the arrangement.
    parent_id: str | None = Field(default=None, description="Parent description, when the source declares one.")
    path: str | None = Field(
        default=None,
        description="Materialised path; omit it and the row is inserted as a root and never re-rooted.",
    )

    execution_log: dict[str, str] = Field(
        default_factory=dict,
        description="Tracks which workers (AI) have already processed the document. E.g.: {'ner_spacy': 'DONE'}",
    )

    # --- Governance (Human-In-The-Loop) ---
    review_status: ArchiveReviewStatus = Field(
        default=ArchiveReviewStatus.PENDING_AI, description="Current audit status."
    )
    is_anomaly: bool = Field(default=False, description="Structural error flag.")
    anomaly_reasons: list[str] | None = Field(default=None, description="List of errors found.")

    model_config = ConfigDict(from_attributes=True)


class DocumentTagSummary(BaseModel):
    """
    Streamlined tag attached to a document when reading the collection.

    It carries the subject decision that travels with the tag — the macro category and the
    confidence the classifier had — because the subject tab has to show *why* a document is
    filed where it is, and reading it from a second route per tag would be an N+1 on the
    front-end. The data already exists on ``ArchiveTag``; this only stops dropping it.
    """

    tag_id: int
    name: str
    macro_category_id: int | None = None
    macro_category_name: str | None = None
    #: ``None`` when the tag never went through the classifier (no subject decision at all).
    ai_confidence_score: float | None = None

    model_config = ConfigDict(from_attributes=True)


class DocumentEntitySummary(BaseModel):
    """Streamlined named entity (NER) attached to a document."""

    entity_id: int
    name: str
    entity_type: str

    model_config = ConfigDict(from_attributes=True)


class FacetCount(BaseModel):
    """
    One selectable value of a facet, with how many documents the current filters leave.

    ``key`` is what the client sends back as the filter value (``typology_id``, ``level_id``,
    ``entity_type``...), kept as a string so every facet can travel in the query string
    unchanged; ``label`` is what a human reads. They differ for every facet whose value is an
    id rather than a name.
    """

    key: str
    label: str
    count: int


class DocumentFacets(BaseModel):
    """
    Counts for the search sidebar, respecting the filters that are active.

    A facet's own selection does **not** constrain its own counts: with "Dossiê" chosen, the
    level list still shows the other rungs and how many documents each would bring. That is
    what makes the sidebar navigable instead of a dead end — the alternative zeroes every
    option except the selected one, and the user can neither widen nor switch.
    """

    typology: list[FacetCount] = Field(default_factory=list)
    macro_category: list[FacetCount] = Field(default_factory=list)
    entity_type: list[FacetCount] = Field(default_factory=list)
    level: list[FacetCount] = Field(default_factory=list)
    #: Why the quality validator flagged the descriptions. It is **curation metadata**, and the
    #: public projection refuses it on purpose (``NOT_PUBLIC_FACETS``): the diffusion surface has no
    #: business publishing how many records are missing a date.
    anomaly_reason: list[FacetCount] = Field(default_factory=list)


class DocumentMacroCategorySummary(BaseModel):
    """Vote of one macro category over the tags of a document."""

    category_id: int
    name: str
    tag_count: int

    model_config = ConfigDict(from_attributes=True)


class DocumentAncestorSummary(BaseModel):
    """
    One rung of the branch a description sits on, root first.

    Streamlined on purpose: the read view of a collection page needs to *place* the description
    ("this item is inside the Série Registros Fotográficos, under the Fundo IPPUC"), not to repeat
    the whole ISAD(G) record of every ancestor above it.
    """

    description_id: str
    title: str | None = None
    level: str | None = None


class DocumentSummary(BaseModel):
    """Read view of the collection, consumed by the API and the front-end."""

    description_id: str
    original_title: str
    final_title: str | None = None
    document_date: date | None = None
    review_status: ArchiveReviewStatus
    is_anomaly: bool = False
    anomaly_reasons: list[str] | None = Field(default=None, description="Codes written by the quality validator.")
    #: Diffusion decision (Fase 4). Orthogonal to ``review_status``: a record can be corrected
    #: without being published, and publishing it must not lock the AI out of improving it.
    is_published: bool = False
    storage_thumbnail_uri: str | None = None

    # ISAD(G) fields the archivist may correct; exposed so the API can show what is there.
    reference_code: str | None = None
    #: Name of the catalogue rung. Derived from ``level_id`` on read, kept under the same name
    #: the free-text column used to have so no existing consumer has to change.
    level: str | None = None
    level_id: int | None = None
    #: Typology is a facet of the collection, so the read view has to say which one it is without
    #: the client resolving an id per row.
    typology_id: int | None = None
    typology: str | None = None
    #: Position in the arrangement. ``ancestors`` and ``children_count`` are the H8 surface and
    #: are deliberately not exposed yet: the read view grows when the tree is materialised.
    parent_id: str | None = None
    path: str | None = None
    producers: str | None = None
    admin_bio_history: str | None = None
    admin_archival_history: str | None = None
    provenance: str | None = None
    scope_content: str | None = None
    language_name: str | None = None
    archivist_notes: str | None = None
    access_conditions: str | None = Field(
        default=None, description="ISAD(G) 4.1: conditions governing access; the diffusion gate."
    )

    # Derived on read from the title-scoped excerpts: the machine proposes the title
    # without the repeated fixed part, and only the archivist writes ``final_title``.
    suggested_final_title: str | None = Field(
        default=None, description="Title proposal; never stored, disappears once final_title is written."
    )

    #: The branch this description sits on, root first, read from the materialised path — one
    #: query per page, never one per document.
    ancestors: list[DocumentAncestorSummary] = Field(default_factory=list)
    #: How many descriptions hang directly under this one.
    children_count: int = 0

    tags: list[DocumentTagSummary] = Field(default_factory=list)
    entities: list[DocumentEntitySummary] = Field(default_factory=list)
    # Majority vote over ``tags``: how many of this document's tags belong to each
    # macro category, ordered by count. Built by the repository on read.
    macro_categories: list[DocumentMacroCategorySummary] = Field(default_factory=list)
    # Relevance of a free-text search (higher is better). ``None`` when browsing the
    # collection without a term; the page is always ordered by it when present.
    rank: float | None = Field(default=None, description="Full-text relevance score.")

    model_config = ConfigDict(from_attributes=True)


class DocumentRevisionDTO(BaseModel):
    """One entry of the human review audit trail (before/after of every changed field)."""

    revision_id: int
    changed_by: str | None = None
    #: ``{"scope_content": {"old": "...", "new": "..."}}``, only the fields that really changed.
    #: Typed with its value and not as a bare ``dict``: a bare one reaches the generated TypeScript
    #: client as ``Record<string, never>``, which the history screen cannot even index.
    changes: dict[str, Any] = Field(default_factory=dict)
    note: str | None = None
    created_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DocumentDeletionDTO(BaseModel):
    """
    One entry of the deletion ledger: what was removed, when, by whom, and the snapshot of it.

    ``snapshot`` is typed as ``dict[str, Any]`` and not as a bare ``dict`` for the reason the revision
    DTO documents: a bare one reaches the generated TypeScript client as ``Record<string, never>``,
    which the ledger screen cannot even index.
    """

    deletion_id: int
    description_id: str
    reference_code: str | None = None
    title: str
    level_name: str | None = None
    children_count: int = 0
    snapshot: dict[str, Any] = Field(default_factory=dict)
    deleted_by: str | None = None
    note: str | None = None
    deleted_at: datetime

    model_config = ConfigDict(from_attributes=True)


class DocumentDeletionListResponse(BaseModel):
    """One page of the deletion ledger; ``total`` counts every row matching the search."""

    total: int
    limit: int
    offset: int
    items: list[DocumentDeletionDTO] = Field(default_factory=list)


class DocumentDeletionResponse(RouteResponse):
    """
    The answer to a deletion.

    It carries the ledger entry, not the deleted document: the only thing left to read afterwards is
    the snapshot, and returning it here saves the screen a second request to show what was lost.
    """

    data: DocumentDeletionDTO


class DocumentListResponse(BaseModel):
    """
    Page of collection results.

    ``facets`` always comes back, because a search response that sometimes carries the sidebar
    counts and sometimes does not is a worse contract than one that always does — the client
    would have to know *when* to trust the absence. It costs four grouped queries on an
    indexed set, which is small next to the ranking query it accompanies.
    """

    total: int
    limit: int
    offset: int
    items: list[DocumentSummary]
    facets: DocumentFacets = Field(default_factory=DocumentFacets)
