"""
The reference collection's vocabulary, as test data.

The catalogue is **data of the installation**, so it is not in `src/`: a fresh install starts with
an empty vocabulary and loads one with `python -m scrinalia.domains.archive.cli import`. The tests
are a different matter, and deliberately so. They were written *against this collection* — every
spelling below was read from it, with the document count next to it, and that is what makes them
fail when the guard stops covering what it was written for. A neutral placeholder vocabulary would
make the suite green about nothing.

So it lives here, in the test tree, where it is unambiguously fixture data and not the product's
starting state.
"""

ARRANGEMENT_TERMS: tuple[tuple[str, str], ...] = (
    ("BR PRADAP", "Acervo da entidade custodiadora"),
    ("IPPUC", "IPPUC - Instituto de Pesquisa e Planejamento Urbano de Curitiba"),
    ("SMU", "SMU - Secretaria Municipal de Urbanismo"),
    ("SMMA", "SMMA - Secretaria Municipal do Meio Ambiente"),
    ("SEPLAD", "SEPLAD - Secretaria Municipal do Planejamento"),
    ("CMC", "CMC - Câmara Municipal de Curitiba"),
    ("FAS", "FAS - Fundação de Ação Social"),
    ("SGM", "SGM - Secretaria Municipal de Governo"),
    ("SMCS", "SMCS - Secretaria Municipal da Comunicação Social"),
    ("SMDS", "SMDS - Secretaria Municipal da Defesa Social"),
    ("FOTOGRAFIA", "Registros Fotográficos"),
    ("FOTOGRAFIAS", "Registros Fotográficos"),
    ("ED", "Edificações"),
    ("AL", "Alvenaria"),
    ("CONSTR", "Construções"),
    ("CVCO", "Certificados de Vistoria e Conclusão de Obras"),
    ("OUVIDORIA", "Ouvidoria Municipal de Curitiba"),
    ("LEGISLAÇÃO", "Referência Legislativa"),
    ("MICROFILME", "Microfilme"),
    ("PROC", "Processos"),
    ("MATADOURO", "Matadouro Municipal"),
    ("DIAPOSITIVO", "Diapositivos"),
    ("JORN", "Jornais"),
    ("REQUERIMENTOS", "Requerimentos"),
    ("REQ", "Requerimentos"),
    ("OF", "Ofícios"),
    ("HIST", "Histórico"),
    ("PP", "Pareceres e Projetos"),
    ("DUP", "Duplicatas"),
    ("GAZ", "Gazeta"),
    ("MERC", "Mercado"),
    ("ATUBA", "Atuba"),
    ("INVENT", "Inventário"),
    ("MODELO", "Modelo"),
    ("BOMBAS", "Bombas"),
    ("INFLAMAVEIS", "Inflamáveis"),
    ("DEPOSITO", "Depósito"),
    ("PEQ", "Pequenos"),
)

COLLECTION_TERMS: tuple[tuple[str, str], ...] = (
    ("curitiba antiga", "DISTRICT"),
    ("centro", "DISTRICT"),
    ("centro cívico", "DISTRICT"),
    ("centro histórico", "DISTRICT"),
    ("batel", "DISTRICT"),
    ("boqueirão", "DISTRICT"),
    ("alto boqueirão", "DISTRICT"),
    ("campinas", "DISTRICT"),
    ("cajuru", "DISTRICT"),
    ("uberaba", "DISTRICT"),
    ("pinheirinho", "DISTRICT"),
    ("portão", "DISTRICT"),
    ("pilarzinho", "DISTRICT"),
    ("mossunguê", "DISTRICT"),
    ("bigorrilho", "DISTRICT"),
    ("bacacheri", "DISTRICT"),
    ("rebouças", "DISTRICT"),
    ("guabirotuba", "DISTRICT"),
    ("tatuquara", "DISTRICT"),
    ("barreirinha", "DISTRICT"),
    ("juvevê", "DISTRICT"),
    ("capão", "DISTRICT"),
    ("capão da imbuia", "DISTRICT"),
    ("capão raso", "DISTRICT"),
    ("santa felicidade", "DISTRICT"),
    ("alto da glória", "DISTRICT"),
    ("alto da xv", "DISTRICT"),
    ("são francisco", "DISTRICT"),
    ("sítio cercado", "DISTRICT"),
    ("cristo rei", "DISTRICT"),
    ("campo comprido", "DISTRICT"),
    ("prado velho", "DISTRICT"),
    ("vila", "DISTRICT"),
    ("curitiba", "MUNICIPALITY"),
    ("são paulo", "MUNICIPALITY"),
    ("joinville", "MUNICIPALITY"),
    ("paris", "MUNICIPALITY"),
    ("zurique", "MUNICIPALITY"),
    ("zurich", "MUNICIPALITY"),
    ("washington", "MUNICIPALITY"),
    ("campina grande do sul", "MUNICIPALITY"),
    ("araucária", "MUNICIPALITY"),
    ("pinhais", "MUNICIPALITY"),
    ("mandirituba", "MUNICIPALITY"),
    ("balsa nova", "MUNICIPALITY"),
    ("paraná", "STATE"),
    ("santa catarina", "STATE"),
    ("bahia", "STATE"),
    ("região metropolitana de curitiba", "REGION"),
    ("rmc", "REGION"),
    ("australia", "COUNTRY"),
    ("austrália", "COUNTRY"),
    ("suíça", "COUNTRY"),
    ("frança", "COUNTRY"),
    ("alemanha", "COUNTRY"),
    ("jaime lerner", "PERSON"),
    ("oscar niemeyer", "PERSON"),
    ("lúcio costa", "PERSON"),
    ("mário de miranda", "PERSON"),
    ("joel rocha", "PERSON"),
    ("poty lazzarotto", "PERSON"),
    ("tadeusz kościuszko", "PERSON"),
    ("ernesto guaita", "PERSON"),
    ("lina faria", "PERSON"),
    ("michelangelo cuniberti", "PERSON"),
    ("marilia kranz", "PERSON"),
    ("paulo spzak", "PERSON"),
    ("eduardo fernando chaves", "PERSON"),
    ("aristeu dias", "PERSON"),
    ("joão zaco paraná", "PERSON"),
    ("abrão assad", "PERSON"),
)
