from datetime import date, datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    ARRAY,
    Boolean,
    Computed,
    Date,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, TSVECTOR
from sqlalchemy.orm import Mapped, mapped_column, relationship

from memoria_curitibana.core.base import Base

from .enums import ArchiveReviewStatus

if TYPE_CHECKING:
    from .entity import ArchiveEntity
    from .taxonomy import ArchiveTag, ArchiveTypology


# Lexical search vector, computed by PostgreSQL itself.
#
# ``setweight`` gives the titles weight ``A`` and the descriptive body weight ``B``,
# so ``ts_rank`` ranks a title hit above a body hit with no extra plumbing.
# ``immutable_unaccent`` (created by the migration, and by ``testing/conftest.py``)
# makes the search accent-insensitive: without it ``gaucho`` does not find ``Gaúcho``.
# The expression must stay byte-identical to the migration that creates the column;
# Alembic only warns crudely when a computed expression changes.
DOCUMENT_SEARCH_VECTOR_SQL = (
    "setweight(to_tsvector('portuguese', public.immutable_unaccent("
    "coalesce(final_title, '') || ' ' || coalesce(original_title, ''))), 'A')"
    " || "
    "setweight(to_tsvector('portuguese', public.immutable_unaccent("
    "coalesce(scope_content, '') || ' ' || coalesce(admin_bio_history, '') || ' ' || coalesce(provenance, ''))), 'B')"
)


class ArchiveDocument(Base):
    """
    The final, cleaned and enriched document.

    This is the central database served to end users,
    fed by multiple asynchronous Artificial Intelligence workers.
    """

    __tablename__ = "archive_documents"

    description_id: Mapped[str] = mapped_column(String(50), primary_key=True)

    # --- Lineage and Origin ---
    original_title: Mapped[str] = mapped_column(Text, nullable=False)
    document_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    summary: Mapped[str | None] = mapped_column(Text, nullable=True)
    staging_content_hash: Mapped[str] = mapped_column(String(64), nullable=False)
    original_thumbnail_url: Mapped[str | None] = mapped_column(String, nullable=True)
    storage_thumbnail_uri: Mapped[str | None] = mapped_column(String, nullable=True)

    # --- Archival Metadata (ISAD-G) ---
    reference_code: Mapped[str | None] = mapped_column(Text, nullable=True)
    level: Mapped[str | None] = mapped_column(Text, nullable=True)
    producers: Mapped[str | None] = mapped_column(Text, nullable=True)
    admin_bio_history: Mapped[str | None] = mapped_column(Text, nullable=True)
    admin_archival_history: Mapped[str | None] = mapped_column(Text, nullable=True)
    provenance: Mapped[str | None] = mapped_column(Text, nullable=True)
    scope_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    language_name: Mapped[str | None] = mapped_column(Text, nullable=True)
    archivist_notes: Mapped[str | None] = mapped_column(Text, nullable=True)

    # --- NLP/AI Enrichment ---
    final_title: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Generated by PostgreSQL from the text columns above: it is never written by
    # workers, so it cannot go stale after a human review either. See
    # ``DOCUMENT_SEARCH_VECTOR_SQL`` for the expression and the GIN index below.
    search_vector: Mapped[str | None] = mapped_column(
        TSVECTOR,
        Computed(DOCUMENT_SEARCH_VECTOR_SQL, persisted=True),
        nullable=True,
    )

    # Example: {"ner_spacy_v1": "DONE", "mdeberta_tags": "PENDING"}
    execution_log: Mapped[dict] = mapped_column(JSONB, default=dict)
    typology_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("archive_typologies.typology_id", ondelete="SET NULL"), nullable=True, index=True
    )

    # --- Audit (Human-in-the-Loop) ---
    # ``create_type=True`` here is the single owner of the native enum type; the
    # other table that uses ArchiveReviewStatus passes ``create_type=False`` so a
    # ``metadata.create_all`` creates the type exactly once.
    review_status: Mapped[ArchiveReviewStatus] = mapped_column(
        Enum(ArchiveReviewStatus, name="archive_review_status_enum", create_type=True),
        default=ArchiveReviewStatus.PENDING_AI,
        nullable=False,
        index=True,
    )
    is_anomaly: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    anomaly_reasons: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)

    # --- Relationships---
    entities: Mapped[list["ArchiveEntity"]] = relationship(
        secondary="archive_document_entities", back_populates="descriptions"
    )
    tags: Mapped[list["ArchiveTag"]] = relationship(secondary="archive_document_tags", back_populates="descriptions")
    typology: Mapped["ArchiveTypology"] = relationship(back_populates="documents")

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    __table_args__ = (
        # The GIN index is vital for the AI Workers' polling performance
        Index("ix_archive_exec_log", execution_log, postgresql_using="gin"),
        # Native full-text search over the generated ``search_vector`` column.
        Index("ix_archive_documents_search_vector", "search_vector", postgresql_using="gin"),
    )
