"""initial schema

Revision ID: a5cc7ec65348
Revises:
Create Date: 2026-10-01 20:17:54.224280

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5cc7ec65348"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # pg_trgm powers the fuzzy-search GIN indexes created below.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_ai_review_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("anomaly_type", sa.Enum("CROSS_DOMAIN_COLLISION", name="anomaly_type_enum"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_AI",
                "AI_APPROVED",
                "NEEDS_REVIEW",
                "HUMAN_APPROVED",
                "REJECTED",
                name="archive_review_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("context_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("llm_decision", sa.String(length=50), nullable=True),
        sa.Column("llm_confidence", sa.Float(), nullable=True),
        sa.Column("llm_reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_archive_ai_review_queue_anomaly_type"), "archive_ai_review_queue", ["anomaly_type"], unique=False
    )
    op.create_index(op.f("ix_archive_ai_review_queue_status"), "archive_ai_review_queue", ["status"], unique=False)
    op.create_table(
        "archive_cleaning_rules",
        sa.Column("rule_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("rule_name", sa.String(length=150), nullable=False),
        sa.Column("target_column", sa.String(length=50), nullable=False),
        sa.Column("regex_pattern", sa.Text(), nullable=False),
        sa.Column("replacement_string", sa.Text(), server_default="", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("rule_id"),
    )
    op.create_index(op.f("ix_archive_cleaning_rules_is_active"), "archive_cleaning_rules", ["is_active"], unique=False)
    op.create_table(
        "archive_entities",
        sa.Column("entity_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_index(
        "idx_archive_entities_name_trgm",
        "archive_entities",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_archive_entities_entity_type"), "archive_entities", ["entity_type"], unique=False)
    op.create_index(op.f("ix_archive_entities_name"), "archive_entities", ["name"], unique=True)
    op.create_table(
        "archive_macro_categories",
        sa.Column("category_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
    )
    op.create_index(op.f("ix_archive_macro_categories_name"), "archive_macro_categories", ["name"], unique=True)
    op.create_table(
        "archive_typologies",
        sa.Column("typology_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("context_description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("typology_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "domain_stopwords",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column("word_scope", sa.Enum("TAG", "ENTITY", "ALL", name="stopwords_scope"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domain_stopwords_word"), "domain_stopwords", ["word"], unique=True)
    op.create_index(op.f("ix_domain_stopwords_word_scope"), "domain_stopwords", ["word_scope"], unique=False)
    op.create_table(
        "raw_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description_id", sa.String(length=60), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_title", sa.String(length=500), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description_id"),
    )
    op.create_table(
        "scraping_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description_id", sa.String(length=60), nullable=False),
        sa.Column(
            "scrape_status",
            sa.Enum("PENDING", "DONE", "NETWORK_ERROR", "NOT_FOUND", "FATAL_ERROR", name="scrape_status_enum"),
            nullable=False,
        ),
        sa.Column("discovered_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("last_scraped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("description_id"),
    )
    op.create_table(
        "staging_documents",
        sa.Column("description_id", sa.String(length=50), nullable=False),
        sa.Column("raw_content_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("attachment_link", sa.Text(), nullable=True),
        sa.Column("thumb_down_link", sa.Text(), nullable=True),
        sa.Column("reference_code", sa.Text(), nullable=True),
        sa.Column("level", sa.Text(), nullable=True),
        sa.Column("dimension_support", sa.Text(), nullable=True),
        sa.Column("producers", sa.Text(), nullable=True),
        sa.Column("admin_bio_history", sa.Text(), nullable=True),
        sa.Column("admin_archival_history", sa.Text(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("scope_content", sa.Text(), nullable=True),
        sa.Column("appraisal_destruction", sa.Text(), nullable=True),
        sa.Column("accruals", sa.Text(), nullable=True),
        sa.Column("arrangement", sa.Text(), nullable=True),
        sa.Column("access_conditions", sa.Text(), nullable=True),
        sa.Column("reproduction_conditions", sa.Text(), nullable=True),
        sa.Column("language_name", sa.Text(), nullable=True),
        sa.Column("physical_characteristics", sa.Text(), nullable=True),
        sa.Column("finding_aids", sa.Text(), nullable=True),
        sa.Column("originals_location", sa.Text(), nullable=True),
        sa.Column("copies_location", sa.Text(), nullable=True),
        sa.Column("related_units", sa.Text(), nullable=True),
        sa.Column("publication_notes", sa.Text(), nullable=True),
        sa.Column("conservation_notes", sa.Text(), nullable=True),
        sa.Column("general_notes", sa.Text(), nullable=True),
        sa.Column("archivist_notes", sa.Text(), nullable=True),
        sa.Column("rules_conventions", sa.Text(), nullable=True),
        sa.Column("description_dates", sa.Text(), nullable=True),
        sa.Column("indexing_points", sa.Text(), nullable=True),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("description_id"),
    )
    op.create_table(
        "archive_documents",
        sa.Column("description_id", sa.String(length=50), nullable=False),
        sa.Column("original_title", sa.Text(), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("staging_content_hash", sa.String(length=64), nullable=False),
        sa.Column("original_thumbnail_url", sa.String(), nullable=True),
        sa.Column("storage_thumbnail_uri", sa.String(), nullable=True),
        sa.Column("reference_code", sa.Text(), nullable=True),
        sa.Column("level", sa.Text(), nullable=True),
        sa.Column("producers", sa.Text(), nullable=True),
        sa.Column("admin_bio_history", sa.Text(), nullable=True),
        sa.Column("admin_archival_history", sa.Text(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=True),
        sa.Column("scope_content", sa.Text(), nullable=True),
        sa.Column("language_name", sa.Text(), nullable=True),
        sa.Column("archivist_notes", sa.Text(), nullable=True),
        sa.Column("final_title", sa.Text(), nullable=True),
        sa.Column("semantic_search_vector", sa.Text(), nullable=True),
        sa.Column("execution_log", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("typology_id", sa.Integer(), nullable=True),
        sa.Column(
            "review_status",
            sa.Enum(
                "PENDING_AI",
                "AI_APPROVED",
                "NEEDS_REVIEW",
                "HUMAN_APPROVED",
                "REJECTED",
                name="archive_review_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("is_anomaly", sa.Boolean(), nullable=False),
        sa.Column("anomaly_reasons", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["typology_id"], ["archive_typologies.typology_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("description_id"),
    )
    op.create_index(op.f("ix_archive_documents_is_anomaly"), "archive_documents", ["is_anomaly"], unique=False)
    op.create_index(op.f("ix_archive_documents_review_status"), "archive_documents", ["review_status"], unique=False)
    op.create_index(op.f("ix_archive_documents_typology_id"), "archive_documents", ["typology_id"], unique=False)
    op.create_index("ix_archive_exec_log", "archive_documents", ["execution_log"], unique=False, postgresql_using="gin")
    op.create_table(
        "archive_tags",
        sa.Column("tag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("macro_category_id", sa.Integer(), nullable=True),
        sa.Column("ai_confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["macro_category_id"], ["archive_macro_categories.category_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_index(
        "idx_archive_tags_name_trgm",
        "archive_tags",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(op.f("ix_archive_tags_macro_category_id"), "archive_tags", ["macro_category_id"], unique=False)
    op.create_index(op.f("ix_archive_tags_name"), "archive_tags", ["name"], unique=True)
    op.create_table(
        "archive_document_entities",
        sa.Column("description_id", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["description_id"], ["archive_documents.description_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["entity_id"], ["archive_entities.entity_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("description_id", "entity_id"),
    )
    op.create_table(
        "archive_document_tags",
        sa.Column("description_id", sa.String(length=50), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["description_id"], ["archive_documents.description_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["archive_tags.tag_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("description_id", "tag_id"),
    )
    op.create_table(
        "domain_synonyms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("synonym_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("canonical_tag_id", sa.Integer(), nullable=True),
        sa.Column("canonical_entity_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "\n            (category = 'TAG' AND canonical_tag_id IS NOT NULL AND canonical_entity_id IS NULL) OR\n            (category IN ('ORG', 'LOC', 'PER') AND canonical_entity_id IS NOT NULL AND canonical_tag_id IS NULL)\n            ",
            name="chk_exclusive_synonym_target",
        ),
        sa.ForeignKeyConstraint(["canonical_entity_id"], ["archive_entities.entity_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["canonical_tag_id"], ["archive_tags.tag_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("synonym_name", "category", name="uix_synonym_category"),
    )
    op.create_index(op.f("ix_domain_synonyms_category"), "domain_synonyms", ["category"], unique=False)
    op.create_index(op.f("ix_domain_synonyms_synonym_name"), "domain_synonyms", ["synonym_name"], unique=False)

    # Keep updated_at accurate even for raw SQL updates (belt-and-suspenders on top
    # of SQLAlchemy's onupdate).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION update_archive_documents_timestamp()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        "CREATE TRIGGER trg_update_archive_documents "
        "BEFORE UPDATE ON archive_documents "
        "FOR EACH ROW EXECUTE FUNCTION update_archive_documents_timestamp()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS trg_update_archive_documents ON archive_documents")
    op.execute("DROP FUNCTION IF EXISTS update_archive_documents_timestamp()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_domain_synonyms_synonym_name"), table_name="domain_synonyms")
    op.drop_index(op.f("ix_domain_synonyms_category"), table_name="domain_synonyms")
    op.drop_table("domain_synonyms")
    op.drop_table("archive_document_tags")
    op.drop_table("archive_document_entities")
    op.drop_index(op.f("ix_archive_tags_name"), table_name="archive_tags")
    op.drop_index(op.f("ix_archive_tags_macro_category_id"), table_name="archive_tags")
    op.drop_index(
        "idx_archive_tags_name_trgm",
        table_name="archive_tags",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("archive_tags")
    op.drop_index("ix_archive_exec_log", table_name="archive_documents", postgresql_using="gin")
    op.drop_index(op.f("ix_archive_documents_typology_id"), table_name="archive_documents")
    op.drop_index(op.f("ix_archive_documents_review_status"), table_name="archive_documents")
    op.drop_index(op.f("ix_archive_documents_is_anomaly"), table_name="archive_documents")
    op.drop_table("archive_documents")
    op.drop_table("staging_documents")
    op.drop_table("scraping_queue")
    op.drop_table("raw_data")
    op.drop_index(op.f("ix_domain_stopwords_word_scope"), table_name="domain_stopwords")
    op.drop_index(op.f("ix_domain_stopwords_word"), table_name="domain_stopwords")
    op.drop_table("domain_stopwords")
    op.drop_table("archive_typologies")
    op.drop_index(op.f("ix_archive_macro_categories_name"), table_name="archive_macro_categories")
    op.drop_table("archive_macro_categories")
    op.drop_index(op.f("ix_archive_entities_name"), table_name="archive_entities")
    op.drop_index(op.f("ix_archive_entities_entity_type"), table_name="archive_entities")
    op.drop_index(
        "idx_archive_entities_name_trgm",
        table_name="archive_entities",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("archive_entities")
    op.drop_index(op.f("ix_archive_cleaning_rules_is_active"), table_name="archive_cleaning_rules")
    op.drop_table("archive_cleaning_rules")
    op.drop_index(op.f("ix_archive_ai_review_queue_status"), table_name="archive_ai_review_queue")
    op.drop_index(op.f("ix_archive_ai_review_queue_anomaly_type"), table_name="archive_ai_review_queue")
    op.drop_table("archive_ai_review_queue")
    # ### end Alembic commands ###
