import re

from sqlalchemy import func, or_, select
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session, selectinload
from sqlalchemy.orm.attributes import flag_modified

from domains.archive.models import (
    ArchiveDocument,
    ArchiveReviewStatus,
)
from domains.archive.schemas.command_schema import DocumentReviewCommand
from domains.archive.schemas.document_schema import ArchiveDocumentDTO, DocumentSummary


class DocumentRepository:
    def __init__(self, db: Session) -> None:
        self.db = db

    def upsert_archive_document(self, doc_data: ArchiveDocumentDTO) -> bool:
        """
        Inserts or updates the fact document in the Archive layer from the Staging data.

        ⚠️ CRITICAL ARCHITECTURE RESTRICTION (EXCLUSIVE USE IN LOAD/MIGRATION):
        This function is designed UNIQUELY for the Staging -> Archive transfer pipeline.
        The UPDATE will only be executed if the incoming 'staging_content_hash'
        is DIFFERENT from the hash currently persisted in Archive (change at the source).

        🚨 IMPORTANT FOR AI PIPELINES (WORKERS):
        DO NOT use this function to save AI enrichments (spaCy, mDeBERTa).
        For Workers, use surgical UPDATE functions (such as stamp_ai_execution),
        otherwise, the ON CONFLICT will block the operation and discard the AI data.

        🔒 GOVERNANCE (HUMAN-IN-THE-LOOP):
        If the document has the 'HUMAN_APPROVED' status, PostgreSQL will block
        any attempt at overwriting, shielding the human review from rollbacks.

        Args:
            db (Session): Active SQLAlchemy session.
            doc_data (ArchiveDocumentDTO): Validated object with ISAD(G) metadata.

        Returns:
            bool: True if the record was created or modified; False if the operation was
                ignored due to Hash consistency or protection of human work.
        """
        db_dict = doc_data.model_dump(exclude_unset=True)

        stmt = insert(ArchiveDocument).values(db_dict)

        # Protects immutable columns or columns that are the exclusive responsibility of Archive.
        protected_columns = [
            "description_id",  # PK (Never changes)
            "created_at",  # Creation date (Never changes)
            "storage_thumbnail_uri",  # Generated by Storage
        ]

        # Only the columns present in the payload are eligible for the UPDATE. Iterating
        # over ``stmt.excluded`` would expose EVERY table column, nulling out fields
        # (ISAD(G) metadata, anomaly flags, ...) that were not part of this transfer.
        update_dict = {key: stmt.excluded[key] for key in db_dict if key not in protected_columns}
        # Only performs the UPDATE if the current status in the database is NOT HUMAN_APPROVED
        stmt = stmt.on_conflict_do_update(
            index_elements=["description_id"],
            set_=update_dict,
            where=(
                (ArchiveDocument.review_status != ArchiveReviewStatus.HUMAN_APPROVED)
                & (ArchiveDocument.staging_content_hash != stmt.excluded.staging_content_hash)
            ),
        )
        stmt = stmt.returning(ArchiveDocument.description_id)

        saved_id = self.db.scalar(stmt)
        return saved_id is not None

    def fetch_documents_for_clustering(self, columns_to_extract: list[str] | None = None) -> list[str]:
        """
        Fetches documents and concatenates the requested textual columns
        into a single cohesive string to feed the AI.
        """
        columns = columns_to_extract or ["original_title", "admin_bio_history", "provenance", "scope_content"]

        filters = [getattr(ArchiveDocument, col).is_not(None) for col in columns]
        stmt = select(ArchiveDocument).where(or_(*filters))

        docs = self.db.scalars(stmt).all()
        clean_txt = []

        for doc in docs:
            parts = []
            for col in columns:
                val = getattr(doc, col)
                # Ensures it is not null, is a string and is not empty (only spaces)
                if val and isinstance(val, str) and val.strip():
                    # Removes line breaks to avoid confusing the algorithm
                    clean_text = re.sub(r"\s+", " ", val.strip())
                    if clean_text:
                        parts.append(clean_text)

            if parts:
                # Joins the Title with the Description using a period and a space
                clean_txt.append(". ".join(parts) + ".")

        return clean_txt

    def stamp_ai_execution(self, description_id: str, worker_name: str) -> None:
        """
        Stamps the document with the signature of the AI Worker that finished the process.
        This prevents the AI from redoing the same work if the server restarts.
        """
        stmt = select(ArchiveDocument).where(ArchiveDocument.description_id == description_id)
        doc = self.db.execute(stmt).scalar_one_or_none()

        if doc:
            new_log = dict(doc.execution_log)
            new_log[worker_name] = "DONE"

            # Replaces and warns SQLAlchemy that the JSON was modified
            doc.execution_log = new_log
            flag_modified(doc, "execution_log")

    # ==========================================
    # READING AND CURATION (HUMAN-IN-THE-LOOP)
    # ==========================================

    def search(self, term: str | None = None, limit: int = 50, offset: int = 0) -> tuple[list[DocumentSummary], int]:
        """
        Simple textual search of the collection with pagination.

        Returns the page of documents (with tags and entities already loaded
        via eager loading, avoiding the N+1 problem) and the total number of records.
        """
        stmt = select(ArchiveDocument)

        if term:
            like = f"%{term}%"
            stmt = stmt.where(
                or_(
                    ArchiveDocument.original_title.ilike(like),
                    ArchiveDocument.final_title.ilike(like),
                    ArchiveDocument.scope_content.ilike(like),
                )
            )

        total = self.db.scalar(select(func.count()).select_from(stmt.subquery())) or 0

        page_stmt = (
            stmt.options(selectinload(ArchiveDocument.tags), selectinload(ArchiveDocument.entities))
            .order_by(ArchiveDocument.updated_at.desc())
            .limit(limit)
            .offset(offset)
        )
        docs = [DocumentSummary.model_validate(doc) for doc in self.db.scalars(page_stmt).all()]
        return docs, total

    def get_by_id(self, description_id: str) -> DocumentSummary | None:
        """Loads a document with tags and entities for reading/editing."""
        stmt = (
            select(ArchiveDocument)
            .where(ArchiveDocument.description_id == description_id)
            .options(selectinload(ArchiveDocument.tags), selectinload(ArchiveDocument.entities))
        )
        doc = self.db.scalars(stmt).first()
        return DocumentSummary.model_validate(doc) if doc else None

    def update_review(self, command: DocumentReviewCommand) -> DocumentSummary | None:
        """
        Applies the archivist's edits and shields the document against the AI.

        Any manually edited document becomes `HUMAN_APPROVED`, which
        prevents overwriting by the migration/AI pipeline.
        """
        doc = self._get_orm_by_id(command.description_id)
        if doc is None:
            return None

        changes = command.model_dump(exclude_unset=True, exclude={"description_id"})
        for field, value in changes.items():
            setattr(doc, field, value)

        doc.review_status = ArchiveReviewStatus.HUMAN_APPROVED
        self.db.flush()
        return DocumentSummary.model_validate(doc)

    def _get_orm_by_id(self, description_id: str) -> ArchiveDocument | None:
        """Internal ORM lookup used by write flows that need the managed entity."""
        stmt = (
            select(ArchiveDocument)
            .where(ArchiveDocument.description_id == description_id)
            .options(selectinload(ArchiveDocument.tags), selectinload(ArchiveDocument.entities))
        )
        return self.db.scalars(stmt).first()
