CREATE TABLE IF NOT EXISTS silver_descriptions (
    description_id VARCHAR(50) PRIMARY KEY,
    bronze_content_hash VARCHAR(64) NOT NULL, -- O Hash para saber se atualizou
    title TEXT NOT NULL,
    document_date DATE,
    original_url TEXT,
    attachment_link TEXT,
    thumb_down_link TEXT,
    -- Metadados da Norma ISAD(G)
    reference_code TEXT,
    level TEXT,
    dimension_support TEXT,
    producers TEXT,
    admin_bio_history TEXT,
    admin_archival_history TEXT,
    provenance TEXT,
    scope_content TEXT,
    appraisal_destruction TEXT,
    accruals TEXT,
    arrangement TEXT,
    access_conditions TEXT,
    reproduction_conditions TEXT,
    language_name TEXT,
    physical_characteristics TEXT,
    finding_aids TEXT,
    originals_location TEXT,
    copies_location TEXT,
    related_units TEXT,
    publication_notes TEXT,
    conservation_notes TEXT,
    general_notes TEXT,
    archivist_notes TEXT,
    rules_conventions TEXT,
    description_dates TEXT,
    indexing_points TEXT,
    raw_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);